export type OrderComputerFlowDataType = {
    productName: string,
    processor: string,
    ram: string,
    hdd: string,
    os: string,
    software: string,
    productPrice: number,
    firstName: string,
    lastName: string,
    email: string,    
    qty: number,
    total: number,
    subTotal: number,
    shipping: number,
    tax: number,
    paymentMethodAdditionalFee: number,
    shippingMethod: string,
    paymentMethod: string,
    paymentInformation: string,    
    company?: string,
    country: string,
    stateProvince?: string, // Optional field for non-US entries
    city: string,
    address1: string,
    address2: string,
    zipOrPostalCode: string,
    cityStateZip: string,
    phoneNumber: string,
    faxNumber?: string // Optional field
}